### ISSUE TITLE
CGAL::Precondition_exception

### ISSUE THREAD

**Issue by 010722** [ShenCiao/Ciallo#4]
The error occurs when I load Bear, Dango, and Totoro model or try to draw self-intersect or intersecting lines. Is there anyone encounter the same issue?

**Comment by ShenCiao** [comment]
That's caused by the kernel type. When developing I disable the CGAL's preconditions. Maybe I ask how did you enable it?

To fix it, change the kernel into `Exact_predicates_exact_constructions_kernel`
https://github.com/ShenCiao/Ciallo/blob/60bb97cdc95b6a21528463c00cf87f83015edb9e/Ciallo/Arrangement.h#L14

**Comment by 010722** [comment]
Thanks! so! much! I'm not sure either how I enable it, maybe some environment issue as you suggested.
